"""Initial schema

Revision ID: 1a0c20cd5286
Revises:
Create Date: 2025-01-01 17:19:21.085090
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a0c20cd5286"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serviceId", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("clientName", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("clientPhone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("clientEmail", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kiwi",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kiwi")
    op.drop_table("appointment")
    # ### end Alembic commands ###
