"""depositToken

Revision ID: 907ca147cafc
Revises: f6d14fcf9ae3
Create Date: 2025-02-02 20:42:24.795118
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907ca147cafc"
down_revision: Union[str, None] = "f6d14fcf9ae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointment",
        sa.Column(
            "depositToken",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "depositToken")
    # ### end Alembic commands ###
