"""Appointment time

Revision ID: e6d41ccbb7ae
Revises: 1a0c20cd5286
Create Date: 2025-01-01 17:23:18.889314
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6d41ccbb7ae"
down_revision: Union[str, None] = "1a0c20cd5286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointment", "time", existing_type=sa.VARCHAR(), type_=sa.Time(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointment", "time", existing_type=sa.Time(), type_=sa.VARCHAR(), existing_nullable=False
    )
    # ### end Alembic commands ###
